
      //This is an autogenerated file. DO NOT MODIFY, your changes will be overwritten.
      import SomeClassThatINeedFromThePlugin from  '@/plugins/fortune-cookie/exports/SomeClassThatINeedFromThePlugin';
      import AnotherClass from  '@/plugins/fortune-cookie/exports/AnotherClass';
      
      const mapping = {
          "fortune-cookie/exports/SomeClassThatINeedFromThePlugin": SomeClassThatINeedFromThePlugin,
          "fortune-cookie/exports/AnotherClass": AnotherClass
      };
      
      //usage: 
      //const AnotherClass = plugin('fortune-cookie/exports/AnotherClass');
      export const plugin = (key) => {
      
          //TODO: key existence checking and fancy regex stuff can go here
          return mapping[key];
      
      };
      