//This is an autogenerated file. DO NOT MODIFY, your changes will be overwritten.
import TestCustomComponent from  '@/plugins/plugin-thirst/exports/TestCustomComponent';

const mapping = {
    "plugin-thirst/exports/TestCustomComponent": TestCustomComponent,
};

// Usage: 
// const AnotherClass = plugin('fortune-cookie/exports/AnotherClass');
// const instance = new AnotherClass();
export const plugin = (key) => {

    //TODO: key existence checking and fancy regex stuff can go here
    return mapping[key];

};
