import { useFormikContext } from "formik";
import { AUTO_PASSWORD, CUSTOM_PASSWORD, writeUsers } from "lib/Constants";
import AdminRenderer from "@/components/renderers/admin/AdminRenderer";
import { useContext, useState } from "react";
import CacheContext from "../contexts/CacheContext";
import PasswordSelection from "../klaudsolcms/selection_controls/PasswordSelection";

export default function PasswordForm({ defaultMode, changePass }) {
    const [passwordMode, setPasswordMode] = useState(defaultMode ?? AUTO_PASSWORD);

    const { values, errors, touched } = useFormikContext();
    const { capabilities } = useContext(CacheContext);

    return (
        <>
            <h4>Password</h4>
            <PasswordSelection passwordMode={passwordMode} setPasswordMode={setPasswordMode} />
            {changePass &&
                <>
                    <p className="general-input-title"> Old Password </p>
                    <AdminRenderer
                        errors={errors}
                        touched={touched}
                        type="password"
                        name="oldPassword"
                        disabled={!capabilities.includes(writeUsers)}
                    />
                </>
            }
            {(passwordMode === AUTO_PASSWORD) &&
                <>
                    <p className="general-input-title"> Autogenerated Password </p>
                    <AdminRenderer
                        errors={errors}
                        touched={touched}
                        type="password"
                        name="password"
                        readOnly={true}
                    />
                </>
            }
            {(passwordMode === CUSTOM_PASSWORD) &&
                <>
                    <p className="general-input-title"> {changePass ? "New Password" : "Password"} </p>
                    <AdminRenderer
                        errors={errors}
                        touched={touched}
                        type="password"
                        name="password"
                        disabled={!capabilities.includes(writeUsers) || passwordMode === AUTO_PASSWORD}
                    />
                    <p className="general-input-title"> {changePass ? "Confirm New Password" : "Confirm Password"} </p>
                    <AdminRenderer
                        errors={errors}
                        touched={touched}
                        type="password"
                        name="confirmPassword"
                        disabled={!capabilities.includes(writeUsers) || passwordMode === AUTO_PASSWORD}
                    />
                </>
            }
            <AdminRenderer
                title="Force password change"
                errors={errors}
                touched={touched}
                type="checkbox"
                name="forcePasswordChange"
                checked={values.forcePasswordChange}
                disabled={!capabilities.includes(writeUsers)}
            />
        </>
    );
}
